name: Run CI
on:
  push:
    branches:
      - master
  pull_request_target:

jobs:
  install_and_check:
    runs-on: ubuntu-latest

    steps:
      - name: Run info
        run: |
          echo trigger [ ${{ github.event_name }} ]
          echo started by "${{ github.triggering_actor }}" running for [ ${{ github.ref_name }} ]
          echo commit: "${{ github.event.head_commit.message }}"
          echo commit_id: "${{ github.event.head_commit.id }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use PNPM
        uses: pnpm/action-setup@v2.4.0

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps (with cache)
        run: pnpm install

      - name: Lint check
        run: pnpm run lint

      - name: Types check
        run: pnpm run types
